# =========================
# 1. FUNDAMENTALS
# =========================
apiVersion: v3.1.0  # Version of the standard used to build data contract. 
kind: DataContract #The kind of file this is.

id: customer_cif_company_shareholder # A unique identifier used to reduce the risk of dataset name collisions.
domain : customer # Name of the logical data domain.
version: 1.0.0 # Current version of the data contract.
status: DRAFT  #Current status of the data contract. Examples are "proposed", "draft", "active", "deprecated", "retired".

description:
  purpose: Ensure data quality and consistency for customer company shareholder # Intended purpose for the provided data.
  usage: Used for reporting and analytics # Recommended usage of the data.
  limitations: Internal use only # Technical, compliance, and legal limitations for data use.

# =========================
# OWNERSHIP
# =========================
team:
  name : regina # The user's name.
  role : data engineer intern #	The user's job role; Examples might be owner, data steward.

# =========================
# INFRASTRUCTURE
# =========================
servers:
  - server: postgres-prod # Identifier of the server.
    type: postgres # Type of the server. Can be one of: hive,  kafka, mysql, postgres, sqlserver, trino, etc.
    database: los # The name of the database.
    schema: bravo_prod # Identify the schema in the data source in which your tables exist.

# =========================
# 3. SCHEMA CONTRACT
# =========================
schema:
- name : customer_cif_company_shareholder # Name of the element.
  physicalType: table # The physical element data type in the data source. For objects: table, view, topic, file
  description: table for customer company shareholder # Description of the element.
  relationships:
  - type: foreignKey 
    from:                     
    - customer_cif_company_shareholder.cif_id   
    to:                       
    - customer_cif.cif_id  

  properties : 
  - name: cif_company_shareholder_id # Name of the properties
    logicalType: string # The logical field datatype. One of string, date, timestamp, number, integer, etc.
    physicalType : varchar(255) # The physical element data type in the data source. For example, VARCHAR(2), DOUBLE, INT.
    primaryKey : true # Boolean value specifying whether the field is primary or not. 
    nullable: false # Indicates if the element may contain Null values; possible values are true and false.
    unique: true # Indicates if the element contains unique values; possible values are true and false.
    criticalDataElement: false # If element is considered a critical data element (CDE) then true else false.
    description: Unique identifier for customer # Description of the properties
  - name: share_percentage
    logicalType: number
    physicalType : numeric
    nullable: false 
    criticalDataElement: true
    description: share percentage
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: name
    logicalType: string
    physicalType : text
    nullable: false 
    criticalDataElement: true
    description: company name
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: address
    logicalType: string 
    physicalType : text 
    nullable: false 
    criticalDataElement: true
    description: alamat
    quality :
      - metric : valueNotContainSpecialCharacter
        description : "name must not contain special character "
        dimension: correctness
        severity: critical
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: subdistrict
    logicalType: string 
    physicalType : text
    nullable: false 
    criticalDataElement: true
    description: kelurahan
  - name: district
    logicalType: string 
    physicalType : text
    nullable: false 
    criticalDataElement: true
    description: kecamatan
  - name: id_type
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: ID Type
    quality : 
      - metric : valueNotInSet
        arguments :
          validValues : ['KTP','E-KTP','PASSPORT']
        dimension: correctness
        severity: warning
  - name: id_number 
    logicalType: string
    physicalType : text
    nullable: false
    unique: true 
    criticalDataElement: true
    description: Nomor Identitas
    quality :
      - metric : regexMatch
        description : "ID Number must be 16-digit numeric for KTP"
        arguments :
          pattern : '^[0-9]{16}$'
        dimension: correctness
        severity: critical
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: gender
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: Jenis Kelamin
    quality : 
      - metric : valueNotInSet
        arguments :
          validValues : ['F','M']
        description: "All values must match one of the defined valid values."
        dimension: correctness
        severity: warning

# =========================
# 4. DATA QUALITY CONTRACT
# =========================
dataQuality:
  - type: library # Type of DQ rule. Valid values are library (default), text, sql, and custom.
    metric : rowCountBetween
    description: "Row count must be between 1 and 1000"
    mustBeGreaterThan: 0
    mustBeLessThan: 1000
# =========================
# 5. FRESHNESS CONTRACT
# =========================
slaProperties:
  - property: latency # A list of key/value pairs for SLA specific properties
    value: 24 # 	Agreement value.
    unit: h # d, day, days for days; y, yr, years for years, etc
    element: customer_cif_company_shareholder.updated_at
    description: Customer CIF company shareholder data latency must not exceed 24 hours # Description of the SLA for humans

# =========================
# 6. CHANGE POLICY
# =========================
changePolicy:
  breakingChange: requires new contract version

# =========================
# 7. METADATA
# =========================
contractCreatedAt: 2026-01-21
    
