
# =========================
# 1. FUNDAMENTALS
# =========================
apiVersion: v3.0.0  # Version of the standard used to build data contract. 
kind: DataContract #The kind of file this is.

id: customer_cif # A unique identifier used to reduce the risk of dataset name collisions, such as a UUID.
domain : customer # Name of the logical data domain.
dataProduct: customer_cif # Name of the data product.
version: 1.0.0 # Current version of the data contract.
status: ACTIVE  #Current status of the data contract. Examples are "proposed", "draft", "active", "deprecated", "retired"..

description:
  purpose: Ensure data quality and consistency for customer data # Intended purpose for the provided data.
  usage: Used for reporting and analytics # Recommended usage of the data.
  limitations: Internal use only # Technical, compliance, and legal limitations for data use.

# =========================
# OWNERSHIP
# =========================
team:
  name : # The user's name.
  description : # description about user
  role : #	The user's job role; Examples might be owner, data steward.

# =========================
# INFRASTRUCTURE
# =========================
servers:
  - server: postgres-prod # Identifier of the server.
    type: postgres # Type of the server. Can be one of: hive,  kafka, mysql, postgres, sqlserver, trino, etc.
    database: los # The name of the database.
    schema: bravo_prod # Identify the schema in the data source in which your tables exist.

# =========================
# 3. SCHEMA CONTRACT
# =========================
schema:
- name : customer_cif # Name of the element.
  physicalType: table # The physical element data type in the data source. For objects: table, view, topic, file
  description: Master table for customer CIF # Description of the element.

  properties : 
  - name: cif_id # Name of the properties
    logicalType: string # The logical field datatype. One of string, date, timestamp, number, integer, etc.
    physicalType : varchar(100) # The physical element data type in the data source. For example, VARCHAR(2), DOUBLE, INT.
    required: true # Indicates if the element may contain Null values; possible values are true and false.
    primaryKey: true # Boolean value specifying whether the field is primary or not.
    unique: true # Indicates if the element contains unique values; possible values are true and false.
    criticalDataElement: true # If element is considered a critical data element (CDE) then true else false.
    description: Unique identifier for customer # Description of the properties
    quality :
      - id : no_nulls # A unique identifier for the element used to create stable, refactor-safe references. 
        metric : nullValues # Required for library: the name of the metric
        mustBe : 0 # The operator specifies the condition to validate a metric or result of a SQL query.
        description : 'There must be no null values in the column' # 	Describe the quality check to be completed.
  - name: id_type
    logicalType: string
    physicalType : varchar
    required: true
    classification: restricted
    criticalDataElement: true
    description: ID Type
    quality :
      - id : id_type_no_nulls # A unique identifier for the element used to create stable, refactor-safe references. 
        metric : nullValues # Required for library: the name of the metric
        mustBe : 0 # The operator specifies the condition to validate a metric or result of a SQL query.
        description : 'There must be no null values in the column' # 	Describe the quality check to be completed.
  - name: id_number 
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Nomor Identitas
  - name: mobile_phone
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: nomor hp
  - name: email
    logicalType: string
    physicalType : varchar
    required: false
    criticalDataElement: true
    description: email
  - name: birth_date
    logicalType: string
    physicalType : varchar(30)
    required: true
    criticalDataElement: true
    description: Customer Birth Date
  - name: birth_place
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Customer birth place
  - name: mother_name
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Customer Mother Name
  - name: spouse_name
    logicalType: string
    physicalType : varchar
    required: false
    criticalDataElement: true
    description: Name of the spouse
  - name: spouse_id_number
    logicalType: string
    physicalType : varchar
    required: false
    criticalDataElement: true
    description: Spouse ID Number
  - name: spouse_birth_date
    logicalType: string
    physicalType : varchar(30)
    required: false
    criticalDataElement: true
    description: Birth date of the spouse
  - name: spouse_birth_place
    logicalType: string
    physicalType : varchar
    required: false
    criticalDataElement: true
    description: Birth place of the spouse
  - name: monthly_income
    logicalType: number
    physicalType : double
    required: true
    criticalDataElement: true
    description: Monthly income of customer
  - name: num_dependent
    logicalType: string
    physicalType : integer
    required: true
    criticalDataElement: true
    description: Jumlah tanggungan
  - name: emergency_relation
    logicalType: string
    physicalType : varchar
    required: false
    criticalDataElement: true
    description: Hubungan kontak darurat dengan customer
  - name: emergency_name
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Nama kontak darurat
  - name: emergency_number
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: No telepon kontak darurat
  - name: npwp
    logicalType: string
    physicalType : varchar(20)
    required: false
    criticalDataElement: true
    description: npwp
  - name: gender
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Jenis Kelamin
  - name: company_name
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Company Name
  - name: legal_name
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: nama lengkap sesuai ktp
  - name: spouse_legal_name
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: nama lengkap pasangan sesuai ktp
  - name: npwp_type
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: Tipe npwp
  - name: spouse_mobile_phone
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: spouse mobile phone
  - name: home_owner_name
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: home owner name
  - name: employment_since_year
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: year of starting work
  - name: stay_since_year
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: year of starting stay
  - name: home_location
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description: home location
  - name: home_price
    logicalType: string
    physicalType : varchar
    required: false
    criticalDataElement: true
    description: home price
  - name: number_of_employees
    logicalType: number
    physicalType : double
    required: false
    criticalDataElement: true
    description: number of employees
  - name: monthly_variable_income
    logicalType: number
    physicalType : double
    required: true
    criticalDataElement: true
    description : monthly variable income
  - name: nationality
    logicalType: string
    physicalType : varchar
    required: true
    criticalDataElement: true
    description : nationality
  - name: id_number_expiration_date
    logicalType: string
    physicalType : varchar(30)
    required: true
    criticalDataElement: true
    description : id number expiration date
  - name: spouse_id_number_expiration_date
    logicalType: string
    physicalType : varchar(30)
    required: true
    criticalDataElement: true
    description : spouse id number expiration date

# =========================
# 4. DATA QUALITY CONTRACT
# =========================
dataQuality:
  - type: sql # Type of DQ rule. Valid values are library (default), text, sql, and custom.
    query: | # Required for sql DQ rules: the SQL query to be executed.
      SELECT COUNT(*) FROM {customer_cif} WHERE {cif_id} IS NOT NULL 
    mustBeGreaterThan: 0
    mustBeLessThan: 1000
# =========================
# 5. FRESHNESS CONTRACT
# =========================
slaProperties:
  - property: latency # A list of key/value pairs for SLA specific properties
    value: 24 # 	Agreement value.
    unit: h # d, day, days for days; y, yr, years for years, etc
    element: customer_cif.updated_at # 	Element(s) to check on.
    description: Customer CIF data latency must not exceed 24 hours # Description of the SLA for humans

# =========================
# 6. METADATA
# =========================
contractCreatedAt: 2026-01-01
