
# =========================
# 1. FUNDAMENTALS
# =========================
apiVersion: v3.1.0  # Version of the standard used to build data contract. 
kind: DataContract #The kind of file this is.

id: customer_cif # A unique identifier used to reduce the risk of dataset name collisions.
domain : customer # Name of the logical data domain.
version: 1.0.0 # Current version of the data contract.
status: ACTIVE  #Current status of the data contract. Examples are "proposed", "draft", "active", "deprecated", "retired".

description:
  purpose: Ensure data quality and consistency for customer data # Intended purpose for the provided data.
  usage: Used for reporting and analytics # Recommended usage of the data.
  limitations: Internal use only # Technical, compliance, and legal limitations for data use.

# =========================
# OWNERSHIP
# =========================
team:
  name : regina # The user's name.
  role : data engineer intern #	The user's job role; Examples might be owner, data steward.

# =========================
# INFRASTRUCTURE
# =========================
servers:
  - server: postgres-prod # Identifier of the server.
    type: postgres # Type of the server. Can be one of: hive,  kafka, mysql, postgres, sqlserver, trino, etc.
    database: los # The name of the database.
    schema: bravo_prod # Identify the schema in the data source in which your tables exist.

# =========================
# 3. SCHEMA CONTRACT
# =========================
schema:
- name : customer_cif # Name of the element.
  physicalType: table # The physical element data type in the data source. For objects: table, view, topic, file
  description: Master table for customer CIF # Description of the element.

  properties : 
  - name: cif_id # Name of the properties
    logicalType: string # The logical field datatype. One of string, date, timestamp, number, integer, etc.
    physicalType : varchar(100) # The physical element data type in the data source. For example, VARCHAR(2), DOUBLE, INT.
    primaryKey : true # Boolean value specifying whether the field is primary or not. 
    nullable: false # Indicates if the element may contain Null values; possible values are true and false.
    unique: true # Indicates if the element contains unique values; possible values are true and false.
    criticalDataElement: false # If element is considered a critical data element (CDE) then true else false.
    description: Unique identifier for customer # Description of the properties
  - name: name
    logicalType: string 
    physicalType : varchar
    nullable: false 
    criticalDataElement: true
    description: name
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric : valueNotContainSpecialCharacter
        description : "name must not contain special character"
        dimension: correctness
        severity: critical
  - name: id_type
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: ID Type
    quality : 
      - metric : valueInSet
        arguments :
          validValues : ['KTP','E-KTP','PASSPORT']
        dimension: correctness
        severity: warning
  - name: id_number 
    logicalType: string
    physicalType : text
    nullable: false
    unique: true 
    criticalDataElement: true
    description: Nomor Identitas
    quality :
      - metric : regexMatch
        description : "ID Number must be 16-digit numeric for KTP"
        arguments :
          pattern : '^[0-9]{16}$'
        dimension: correctness
        severity: critical
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: mobile_phone
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: nomor hp
    quality :
      - metric : valuePhoneNumberFormatValid
        description : "Phone number must follow a valid format"
        dimension: correctness
        severity: warning
      - metric : valuesNotContainDoubleSpacesss
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: email
    logicalType: string
    physicalType : text
    nullable: true
    criticalDataElement: true
    description: email
    quality :
      - metric : valueEmailFormatValid
        description : "Email must follow a valid email address format"
        dimension: correctness
        severity: warning
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: birth_date
    logicalType: date
    physicalType : date
    nullable: false
    criticalDataElement: true
    description: Customer Birth Date
  - name: birth_place
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: Customer birth place
    quality:
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: mother_name
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: Customer Mother Name
    quality:
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: spouse_name
    logicalType: string
    physicalType : text
    nullable: true
    criticalDataElement: true
    description: Name of the spouse
    quality:
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: spouse_id_number
    logicalType: string
    physicalType : text
    nullable: true
    criticalDataElement: true
    description: Spouse ID Number
    quality :
      - metric : regexMatch
        description : "ID Number must be 16-digit numeric for KTP"
        arguments :
          pattern : '^[0-9]{16}$'
        dimension: correctness
        severity: critical
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric: notEqualToField
        description: "Spouse ID number must not be the same as customer ID number"
        arguments:
          compareToField: id_number
        dimension: consistency
        severity: critical
  - name: spouse_birth_date
    logicalType: date
    physicalType : date
    nullable: true
    criticalDataElement: true
    description: Birth date of the spouse
    quality :
      - metric: valueOutOfRange
        description: "Spouse birth date must be on or after 1900-01-01"
        arguments:
          minValue: "1900-01-01"
        dimension: correctness
        severity: critical
  - name: spouse_birth_place
    logicalType: string
    physicalType : text
    nullable: true
    criticalDataElement: true
    description: Birth place of the spouse
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric : valueNotContainSpecialCharacter
        description : "birth place must not contain special character"
        dimension: correctness
        severity: critical
  - name: customer_type
    logicalType: string
    physicalType : text
    nullable: true
    criticalDataElement: true
    description: Customer type
    quality : 
      - metric : valueInSet
        arguments :
          validValues : ['INDIVUAL', 'INSTITUTION']
        dimension: correctness
        severity: warning
  - name: monthly_income
    logicalType: number
    physicalType : double
    nullable: false
    criticalDataElement: true
    description: Monthly income of customer
    quality :
      - metric : valueOutOfRange
        description : "Monthly income must be greater than 1,000,000 and not exceed 17 digits"
        arguments :
          minValue : 1000000
          maxValue : 99999999999999999
        dimension: correctness
        severity: warning
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: num_dependent
    logicalType: number
    physicalType : integer
    nullable: false
    criticalDataElement: true
    description: Jumlah tanggungan
    quality :
      - metric : valueOutOfRange
        description : "num dependent must be greater than or equal 0"
        arguments :
          minValue : 0
        dimension: correctness
        severity: warning
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: npwp
    logicalType: string
    physicalType : varchar(20)
    nullable: true
    criticalDataElement: true
    description: npwp
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: gender
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: Jenis Kelamin
    quality : 
      - metric : valueInSet
        arguments :
          validValues : ['F','M']
        description: "All values must match one of the defined valid values."
        dimension: correctness
        severity: warning
  - name: company_name
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: nama perusahaan
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric : valueNotContainSpecialCharacter
        description : "name must not contain special character ex . - '"
        dimension: correctness
        severity: critical
  - name: legal_name
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: nama lengkap sesuai ktp
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric : valueNotContainSpecialCharacter
        description : "name must not contain special character ex . - '"
        dimension: correctness
        severity: critical
  - name: spouse_legal_name
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: nama lengkap pasangan sesuai ktp
    quality :
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric : valueNotContainSpecialCharacter
        description : "name must not contain special character ex . - '"
        dimension: correctness
        severity: critical
  - name: npwp_type
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: Tipe npwp
    quality : 
      - metric : valueInSet
        arguments :
          validValues : ['NPWP', 'NONPWP', 'SPNPWP']
        description: "All values must match one of the defined valid values."
        dimension: correctness
        severity: warning
  - name: spouse_mobile_phone
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: spouse mobile phone
    quality :
      - metric : valuePhoneNumberFormatValid
        description : "Phone number must follow a valid format"
        dimension: correctness
        severity: warning
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: home_owner_name
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: home owner name
    quality:
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
      - metric : valueNotContainSpecialCharacter
        description : "name must not contain special character"
        dimension: correctness
        severity: critical
  - name: employment_since_year
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: year of starting work
    quality:
    - metric: valueOutOfRange
      description: "Employment since year must be greater than or equal to 1900"
      arguments:
        minValue: 1900
      dimension: correctness
      severity: warning
    - metric : valuesNotContainDoubleSpaces
      description : "Must not contain double spaces"
      dimension: correctness
      severity: critical
  - name: stay_since_year
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: year of starting stay
    quality:
    - metric : valuesNotContainDoubleSpaces
      description : "Must not contain double spaces"
      dimension: correctness
      severity: critical
  - name: home_location
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description: home location
    quality : 
      - metric : valueInSet
        arguments :
          validValues : ['N', 'K', 'S', 'M']
        description: "N : Menengah, K : Perkampungan, S : Sederhana, M : Perum Mewah"
        dimension: correctness
        severity: warning
  - name: number_of_employees
    logicalType: number
    physicalType : numeric
    nullable: true
    criticalDataElement: true
    description: number of employees
    quality :
      - metric : valueOutOfRange
        description : "number of employees must be greater than 0"
        arguments :
          minValue : 1
        dimension: correctness
        severity: warning
      - metric : valuesNotContainDoubleSpaces
        description : "Must not contain double spaces"
        dimension: correctness
        severity: critical
  - name: nationality
    logicalType: string
    physicalType : text
    nullable: false
    criticalDataElement: true
    description : nationality
    quality : 
      - metric : valueInSet
        arguments :
          validValues : ['WNI', 'WNA']
        dimension: correctness
        severity: critical
  - name: id_number_expiration_date
    logicalType: date
    physicalType : date
    nullable: false
    criticalDataElement: true
    description : id number expiration date
    quality :
      - metric : columnGreaterThan
        description: "ID number expiration date must be later than record creation date"
        arguments :
          compareColumn: created_at
        dimension: correctness
        severity: critical
  - name: spouse_id_number_expiration_date
    logicalType: date
    physicalType : date
    nullable: false
    criticalDataElement: true
    description : spouse id number expiration date
    quality :
      - metric : columnGreaterThan
        description: "ID number expiration date must be later than record creation date"
        arguments :
          compareColumn: created_at
        dimension: correctness
        severity: critical

# =========================
# 4. DATA QUALITY CONTRACT
# =========================
dataQuality:
  - metric : rowCountBetween
    description: "Row count must be between 1 and 1000"
    mustBeGreaterThan: 0
    mustBeLessThan: 1000
# =========================
# 5. FRESHNESS CONTRACT
# =========================
slaProperties:
  - property: latency # A list of key/value pairs for SLA specific properties
    value: 24 # 	Agreement value.
    unit: h # d, day, days for days; y, yr, years for years, etc
    element: customer_cif.updated_at # 	Element(s) to check on.
    description: Customer CIF data latency must not exceed 24 hours # Description of the SLA for humans

# =========================
# 6. CHANGE POLICY
# =========================
changePolicy:
  breakingChange: requires new contract version

# =========================
# 7. METADATA
# =========================
contractCreatedAt: 2026-01-21
