apiVersion: v3.1.0
kind: DataContract
id: confins_r3.ar_agrmnt
version: 1.0.0
status: DRAFT
description:
  purpose: ''
  usage: ''
  limitations: ''
team:
  name: ''
  role: ''
servers:
- server: holo-bravo-prod
  type: postgres
  database: los
  schema: confins_r3
schema:
- name: ar_agrmnt
  physicalType: table
  description: ''
  relationships: []
  properties:
  - name: agrmnt_id
    logicalType: ''
    physicalType: bigint
    nullable: false
    primaryKey: true
    unique: true
    criticalDataElement: false
    description: ''
    quality: []
  - name: cwr_no
    logicalType: ''
    physicalType: character varying(100)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: curr_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: office_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: agrmnt_no
    logicalType: ''
    physicalType: character varying(100)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: cust_no
    logicalType: ''
    physicalType: character varying(100)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: spouse_no
    logicalType: ''
    physicalType: character varying(100)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: num_of_asset
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: tenor
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: pay_freq_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: num_of_inst
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: cumulative_tenor
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: interest_type
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: inst_scheme
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: step_up_down_type
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: grace_period_lc
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: mr_lc_calc_method_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: total_asset_price
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: total_down_payment_gross_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: total_down_payment_nett_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: ntf_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: ins_capitalized_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: os_principal_undue_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: os_interest_undue_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: os_principal_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: os_interest_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: tdp_paid_coy_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: diff_rate_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: next_inst_due_num
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: next_inst_num
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: next_inst_due_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: next_inst_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: next_inst_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: contract_stat_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: default_stat_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: agrmnt_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: go_live_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: go_live_by
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: pre_go_live_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: effective_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: maturity_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: prepaid_hold_stat_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: lc_inst_rate_prml
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: lc_ins_rate_prml
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: effective_rate_prcnt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: flat_rate_prcnt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: grace_period
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: grace_period_type
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: mr_first_inst_type_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: notes
    logicalType: ''
    physicalType: character varying(4000)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: lbppms_clctblty_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: app_no
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: prod_offering_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: prod_offering_version
    logicalType: ''
    physicalType: character varying(20)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: virtual_acc_no
    logicalType: ''
    physicalType: character varying(100)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: mr_wop_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: inst_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: floating_next_review_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: start_floating_inst
    logicalType: ''
    physicalType: integer
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: ref_prod_type_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: lob_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: is_coll_block
    logicalType: ''
    physicalType: boolean
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: baloon_value_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: lc_inst_admin_fee_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: floating_period_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: journal_no
    logicalType: ''
    physicalType: character varying(100)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: biz_template_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: lms_schm_h_id
    logicalType: ''
    physicalType: bigint
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: exp_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: inst_rounding
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: final_gross_yield_prcnt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: usr_crt
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: usr_upd
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: dtm_crt
    logicalType: ''
    physicalType: timestamp without time zone
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: dtm_upd
    logicalType: ''
    physicalType: timestamp without time zone
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: integrity_value
    logicalType: ''
    physicalType: character varying(500)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: gross_yield_prcnt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: cwr_version
    logicalType: ''
    physicalType: bigint
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: total_income_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: total_recog_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: last_amendment_effective_dt
    logicalType: ''
    physicalType: date
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: interest_paid_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: principal_paid_amt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: floating_margin_rate_prcnt
    logicalType: ''
    physicalType: numeric
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: floating_ref_rate_code
    logicalType: ''
    physicalType: character varying(50)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: source_ts_ms
    logicalType: ''
    physicalType: timestamp without time zone
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: operation_ts_ms
    logicalType: ''
    physicalType: timestamp without time zone
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: is_deleted
    logicalType: ''
    physicalType: boolean
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: op
    logicalType: ''
    physicalType: character varying(5)
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
  - name: inserted_date
    logicalType: ''
    physicalType: timestamp without time zone
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality: []
dataQuality: []
slaProperties: []
changePolicy:
  breakingChange: requires new contract version
metadata:
  contractCreatedAt: '2026-02-24'
  contractGeneratedBy: auto-holo-script
  notes: ''
