apiVersion: v3.1.0
kind: DataContract
id: feature_engineering_dev.fea_thm_debt_to_income_ratio
version: 1.0.0
status: DRAFT
description:
  purpose: ''
  usage: ''
  limitations: ''
team:
  name: ''
  role: ''
servers:
- server: trino-bravo-nonprod
  type: trino
  catalog: hive
  schema: feature_engineering_dev
schema:
- name: fea_thm_debt_to_income_ratio
  physicalType: table
  description: ''
  relationships: []
  properties:
  - name: applicationid
    logicalType: string
    physicalType: varchar
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valuesNotContainDoubleSpace
      description: ''
      dimension: correctness
      severity: critical
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
  - name: monthlyfixedincome
    logicalType: number
    physicalType: double
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valueOutOfRange
      description: ''
      arguments:
        minValue: 0
      dimension: correctness
      severity: warning
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
  - name: monthlyvariableincome
    logicalType: number
    physicalType: double
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valueOutOfRange
      description: ''
      arguments:
        minValue: 0
      dimension: correctness
      severity: warning
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
  - name: spouseincome
    logicalType: number
    physicalType: double
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valueOutOfRange
      description: ''
      arguments:
        minValue: 0
      dimension: correctness
      severity: warning
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
  - name: amount_to_be_paid
    logicalType: number
    physicalType: double
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valueOutOfRange
      description: ''
      arguments:
        minValue: 0
      dimension: correctness
      severity: warning
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
  - name: debt_to_income_ratio
    logicalType: number
    physicalType: double
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valueOutOfRange
      description: ''
      arguments:
        minValue: 0
      dimension: correctness
      severity: warning
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
  - name: dt
    logicalType: string
    physicalType: varchar
    nullable: true
    primaryKey: false
    unique: false
    criticalDataElement: false
    description: ''
    quality:
    - metric: valuesNotContainDoubleSpace
      description: ''
      dimension: correctness
      severity: critical
    - metric: valuesNotNull
      description: ''
      dimension: completeness
      severity: critical
dataQuality: []
slaProperties: []
changePolicy:
  breakingChange: requires new contract version
metadata:
  contractCreatedAt: '2026-03-31'
  contractGeneratedBy: auto-trino-script
  notes: ''
